import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import { Asset } from 'expo-asset';
import { unzipSync } from 'fflate';

// ─── Types ────────────────────────────────────────────────────────────────────

export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export interface Topic {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
}

export interface Level {
  id: string;
  topic_id: string;
  title: string;
  description: string;
  difficulty: CEFRLevel;
  date_added: string;
  total_phrases: number;
  source: string;
}

export interface Phrase {
  id: string;
  level_id: string;
  spanish: string;
  english: string;
  grammar_focus?: string;
  tip?: string;
  audio_path: string;
  sort_order: number;
}

export type PhraseRating = 'easy' | 'ok' | 'hard';

export interface PhraseProg {
  rating: number;
  seenCount: number;
  lastRating: PhraseRating | null;
  lastSeenAt: number | null;
}

const DEFAULT_PHRASE_PROG: PhraseProg = {
  rating: 0,
  seenCount: 0,
  lastRating: null,
  lastSeenAt: null,
};

// Migración desde el esquema antiguo ({ learned: boolean; seenCount: number }).
// Devuelve true si se detectó y migró alguna entry legacy.
function migrateLegacyPhraseProgress(
  old: Record<string, any>
): { migrated: Record<string, PhraseProg>; didMigrate: boolean } {
  const migrated: Record<string, PhraseProg> = {};
  let didMigrate = false;
  for (const [key, entry] of Object.entries(old ?? {})) {
    if (entry && typeof entry.learned === 'boolean') {
      didMigrate = true;
      migrated[key] = {
        rating: entry.learned ? -3 : 0,
        seenCount: entry.seenCount ?? 0,
        lastRating: entry.learned ? 'easy' : null,
        lastSeenAt: null,
      };
    } else if (entry && typeof entry.rating === 'number') {
      migrated[key] = {
        rating: entry.rating,
        seenCount: entry.seenCount ?? 0,
        lastRating: entry.lastRating ?? null,
        lastSeenAt: entry.lastSeenAt ?? null,
      };
    }
  }
  return { migrated, didMigrate };
}

export interface LevelProg {
  completedSessions: number;
  lastPlayedAt: string | null;
  totalListens: number;
  totalTimeSeconds: number;
}

// ─── In-memory store ──────────────────────────────────────────────────────────

let topics: Topic[] = [];
let levels: Level[] = [];
let phrases: Phrase[] = [];
let phraseProgress: Record<string, PhraseProg> = {};
let levelProgress: Record<string, LevelProg> = {};


// ─── BUNDLED ZIPS — generated by admin/sync_mobile.py ────────────────────────
const BUNDLED_ZIPS: Record<string, any> = {
};
// ─── END BUNDLED ZIPS ─────────────────────────────────────────────────────────

const PROGRESS_KEY = 'progress';
const LEVELS_DIR = () => FileSystem.documentDirectory + 'levels/';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = '';
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length)));
  }
  return btoa(binary);
}

function base64ToUint8(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function extractZipBytes(bytes: Uint8Array, destDir: string): Promise<void> {
  const files = unzipSync(bytes);
  for (const [filePath, data] of Object.entries(files)) {
    if (filePath.endsWith('/')) continue;
    const fullPath = destDir + filePath;
    const dir = fullPath.substring(0, fullPath.lastIndexOf('/') + 1);
    await FileSystem.makeDirectoryAsync(dir, { intermediates: true }).catch(() => {});
    await FileSystem.writeAsStringAsync(fullPath, uint8ToBase64(data), {
      encoding: FileSystem.EncodingType.Base64,
    });
  }
}

// ─── Progress persistence ─────────────────────────────────────────────────────

export async function loadProgress(): Promise<void> {
  const raw = await AsyncStorage.getItem(PROGRESS_KEY);
  if (!raw) return;
  const p = JSON.parse(raw);
  const { migrated, didMigrate } = migrateLegacyPhraseProgress(p.phraseProgress ?? {});
  phraseProgress = migrated;
  levelProgress = p.levelProgress ?? {};
  if (didMigrate) {
    await saveProgress();
  }
}

export async function saveProgress(): Promise<void> {
  await AsyncStorage.setItem(PROGRESS_KEY, JSON.stringify({ phraseProgress, levelProgress }));
}

// ─── Level management ─────────────────────────────────────────────────────────

const BUNDLED_MANIFEST_PATH = () => LEVELS_DIR() + '.bundled-manifest.json';

async function readBundledManifest(): Promise<Record<string, string>> {
  try {
    const raw = await FileSystem.readAsStringAsync(BUNDLED_MANIFEST_PATH());
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

async function writeBundledManifest(manifest: Record<string, string>): Promise<void> {
  await FileSystem.writeAsStringAsync(BUNDLED_MANIFEST_PATH(), JSON.stringify(manifest));
}

export async function extractBundledLevels(): Promise<void> {
  const levelsDir = LEVELS_DIR();
  await FileSystem.makeDirectoryAsync(levelsDir, { intermediates: true }).catch(() => {});

  const manifest = await readBundledManifest();
  let manifestChanged = false;

  for (const [levelId, module] of Object.entries(BUNDLED_ZIPS)) {
    const levelDir = levelsDir + levelId + '/';
    const asset = Asset.fromModule(module);
    await asset.downloadAsync();
    const assetKey = asset.hash ?? asset.localUri ?? '';

    const info = await FileSystem.getInfoAsync(levelDir);
    const topicInfo = await FileSystem.getInfoAsync(levelDir + 'topic.json');
    const alreadyExtracted = info.exists && topicInfo.exists;
    const manifestMatches = manifest[levelId] === assetKey;
    if (alreadyExtracted && manifestMatches) continue;

    // Re-extracción: borra el directorio previo para evitar mezclar ficheros obsoletos
    if (info.exists) {
      await FileSystem.deleteAsync(levelDir, { idempotent: true });
    }

    const zipB64 = await FileSystem.readAsStringAsync(asset.localUri!, {
      encoding: FileSystem.EncodingType.Base64,
    });
    await extractZipBytes(base64ToUint8(zipB64), levelsDir);
    manifest[levelId] = assetKey;
    manifestChanged = true;
  }

  if (manifestChanged) {
    await writeBundledManifest(manifest);
  }
}

export async function scanInstalledLevels(): Promise<void> {
  topics = [];
  levels = [];
  phrases = [];

  const levelsDir = LEVELS_DIR();
  const entries = await FileSystem.readDirectoryAsync(levelsDir).catch(() => [] as string[]);
  for (const levelId of entries.sort()) {
    if (levelId.startsWith('.')) continue;
    const levelDir = levelsDir + levelId + '/';
    try {
      const metaRaw = await FileSystem.readAsStringAsync(levelDir + 'meta.json');
      const phrasesRaw = await FileSystem.readAsStringAsync(levelDir + 'phrases.json');
      const meta = JSON.parse(metaRaw);
      const phraseList: { spanish: string; english: string; grammar_focus?: string; tip?: string }[] = JSON.parse(phrasesRaw);

      levels.push({
        id: meta.id,
        topic_id: meta.topicId,
        title: meta.title,
        description: meta.description ?? '',
        difficulty: meta.difficulty,
        date_added: meta.dateAdded,
        total_phrases: phraseList.length,
        source: meta.source ?? 'bundled',
      });

      phraseList.forEach((p, i) => {
        const sortOrder = i + 1;
        const padded = String(sortOrder).padStart(3, '0');
        phrases.push({
          id: `${levelId}-${sortOrder}`,
          level_id: levelId,
          spanish: p.spanish,
          english: p.english,
          grammar_focus: p.grammar_focus || undefined,
          tip: p.tip || undefined,
          audio_path: `${levelDir}audio/${padded}.mp3`,
          sort_order: sortOrder,
        });
      });
    } catch (e) {
      console.warn(`[appStore] Error cargando level ${levelId}:`, e);
    }
  }

  const topicsById = new Map<string, Topic>();
  for (const level of levels) {
    if (!topicsById.has(level.topic_id)) {
      try {
        const topicRaw = await FileSystem.readAsStringAsync(LEVELS_DIR() + level.id + '/topic.json');
        topicsById.set(level.topic_id, JSON.parse(topicRaw));
      } catch {
        // Sin topic.json: el level queda silenciosamente sin topic visible
      }
    }
  }

  topics = [...topicsById.values()].sort((a, b) => a.title.localeCompare(b.title, 'es'));
}

export async function installDownloadedLevel(zipPath: string): Promise<void> {
  const zipB64 = await FileSystem.readAsStringAsync(zipPath, {
    encoding: FileSystem.EncodingType.Base64,
  });
  await extractZipBytes(base64ToUint8(zipB64), LEVELS_DIR());
  await scanInstalledLevels();
}

// ─── Store accessors ──────────────────────────────────────────────────────────

export function getTopicsFromStore(): Topic[] { return topics; }
export function getLevelsFromStore(): Level[] { return levels; }
export function getPhrasesFromStore(): Phrase[] { return phrases; }
export function getPhraseProgressFromStore(): Record<string, PhraseProg> { return phraseProgress; }
export function getLevelProgressFromStore(): Record<string, LevelProg> { return levelProgress; }

export function setPhraseProgressEntry(phraseId: string, data: Partial<PhraseProg>): void {
  phraseProgress[phraseId] = {
    ...(phraseProgress[phraseId] ?? DEFAULT_PHRASE_PROG),
    ...data,
  };
}

export function setLevelProgressEntry(levelId: string, data: Partial<LevelProg>): void {
  levelProgress[levelId] = {
    ...(levelProgress[levelId] ?? { completedSessions: 0, lastPlayedAt: null, totalListens: 0, totalTimeSeconds: 0 }),
    ...data,
  };
}

export function deleteLevelFromStore(levelId: string): void {
  levels = levels.filter(l => l.id !== levelId);
  phrases = phrases.filter(p => p.level_id !== levelId);
  for (const key of Object.keys(phraseProgress)) {
    if (key.startsWith(levelId + '-')) delete phraseProgress[key];
  }
  delete levelProgress[levelId];
}
