import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import { Asset } from 'expo-asset';
import { unzipSync } from 'fflate';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface Topic {
  id: string;
  name: string;
  icon: string;
  color: string;
  sort_order: number;
}

export interface Level {
  id: string;
  topic_id: string;
  title: string;
  difficulty: 1 | 2 | 3;
  sort_order: number;
  date_added: string;
  total_phrases: number;
  source: string;
}

export interface Phrase {
  id: string;
  level_id: string;
  spanish: string;
  english: string;
  audio_path: string;
  sort_order: number;
}

export interface PhraseProg {
  learned: boolean;
  seenCount: number;
}

export interface LevelProg {
  completedSessions: number;
  lastPlayedAt: string | null;
}

// ─── In-memory store ──────────────────────────────────────────────────────────

let topics: Topic[] = [];
let levels: Level[] = [];
let phrases: Phrase[] = [];
let phraseProgress: Record<string, PhraseProg> = {};
let levelProgress: Record<string, LevelProg> = {};

// ─── BUNDLED ZIPS — generated by admin/sync_mobile.py ────────────────────────
const BUNDLED_ZIPS: Record<string, any> = {
  'daily-interm-1': require('../../assets/levels/daily-interm-1.zip'),
  'daily-interm-2': require('../../assets/levels/daily-interm-2.zip'),
  'daily-interm-3': require('../../assets/levels/daily-interm-3.zip'),
  'greet-adv-1': require('../../assets/levels/greet-adv-1.zip'),
  'greet-basic-1': require('../../assets/levels/greet-basic-1.zip'),
  'greet-interm-1': require('../../assets/levels/greet-interm-1.zip'),
  'rest-adv-1': require('../../assets/levels/rest-adv-1.zip'),
  'rest-basic-1': require('../../assets/levels/rest-basic-1.zip'),
  'rest-interm-1': require('../../assets/levels/rest-interm-1.zip'),
  'trav-adv-1': require('../../assets/levels/trav-adv-1.zip'),
  'trav-basic-1': require('../../assets/levels/trav-basic-1.zip'),
  'trav-interm-1': require('../../assets/levels/trav-interm-1.zip'),
};
// ─── END BUNDLED ZIPS ─────────────────────────────────────────────────────────

const PROGRESS_KEY = 'progress';
const LEVELS_DIR = () => FileSystem.documentDirectory + 'levels/';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = '';
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length)));
  }
  return btoa(binary);
}

function base64ToUint8(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function extractZipBytes(bytes: Uint8Array, destDir: string): Promise<void> {
  const files = unzipSync(bytes);
  for (const [filePath, data] of Object.entries(files)) {
    if (filePath.endsWith('/')) continue;
    const fullPath = destDir + filePath;
    const dir = fullPath.substring(0, fullPath.lastIndexOf('/') + 1);
    await FileSystem.makeDirectoryAsync(dir, { intermediates: true }).catch(() => {});
    await FileSystem.writeAsStringAsync(fullPath, uint8ToBase64(data), {
      encoding: FileSystem.EncodingType.Base64,
    });
  }
}

// ─── Progress persistence ─────────────────────────────────────────────────────

export async function loadProgress(): Promise<void> {
  const raw = await AsyncStorage.getItem(PROGRESS_KEY);
  if (raw) {
    const p = JSON.parse(raw);
    phraseProgress = p.phraseProgress ?? {};
    levelProgress = p.levelProgress ?? {};
  }
}

export async function saveProgress(): Promise<void> {
  await AsyncStorage.setItem(PROGRESS_KEY, JSON.stringify({ phraseProgress, levelProgress }));
}

// ─── Level management ─────────────────────────────────────────────────────────

export async function extractBundledLevels(): Promise<void> {
  const levelsDir = LEVELS_DIR();
  await FileSystem.makeDirectoryAsync(levelsDir, { intermediates: true }).catch(() => {});

  for (const [levelId, module] of Object.entries(BUNDLED_ZIPS)) {
    const levelDir = levelsDir + levelId + '/';
    const info = await FileSystem.getInfoAsync(levelDir);
    if (info.exists) continue;

    const asset = Asset.fromModule(module);
    await asset.downloadAsync();
    const zipB64 = await FileSystem.readAsStringAsync(asset.localUri!, {
      encoding: FileSystem.EncodingType.Base64,
    });
    await extractZipBytes(base64ToUint8(zipB64), levelsDir);
  }
}

export async function scanInstalledLevels(): Promise<void> {
  topics = [];
  levels = [];
  phrases = [];

  const levelsDir = LEVELS_DIR();
  const entries = await FileSystem.readDirectoryAsync(levelsDir).catch(() => [] as string[]);
  const seenTopics: Record<string, Topic> = {};

  for (const levelId of entries.sort()) {
    const levelDir = levelsDir + levelId + '/';
    try {
      const metaRaw = await FileSystem.readAsStringAsync(levelDir + 'meta.json');
      const phrasesRaw = await FileSystem.readAsStringAsync(levelDir + 'phrases.json');
      const meta = JSON.parse(metaRaw);
      const phraseList: { spanish: string; english: string }[] = JSON.parse(phrasesRaw);

      if (!seenTopics[meta.topicId]) {
        seenTopics[meta.topicId] = {
          id: meta.topicId,
          name: meta.topicName,
          icon: meta.topicIcon,
          color: meta.topicColor,
          sort_order: meta.topicOrder ?? 0,
        };
      }

      levels.push({
        id: meta.id,
        topic_id: meta.topicId,
        title: meta.title,
        difficulty: meta.difficulty,
        sort_order: meta.sort_order ?? 99,
        date_added: meta.dateAdded,
        total_phrases: phraseList.length,
        source: meta.source ?? 'bundled',
      });

      phraseList.forEach((p, i) => {
        const sortOrder = i + 1;
        const padded = String(sortOrder).padStart(3, '0');
        phrases.push({
          id: `${levelId}-${sortOrder}`,
          level_id: levelId,
          spanish: p.spanish,
          english: p.english,
          audio_path: `${levelDir}audio/${padded}.mp3`,
          sort_order: sortOrder,
        });
      });
    } catch (e) {
      console.warn(`[appStore] Error cargando level ${levelId}:`, e);
    }
  }

  topics = Object.values(seenTopics).sort((a, b) => a.sort_order - b.sort_order);
}

export async function installDownloadedLevel(zipPath: string): Promise<void> {
  const zipB64 = await FileSystem.readAsStringAsync(zipPath, {
    encoding: FileSystem.EncodingType.Base64,
  });
  await extractZipBytes(base64ToUint8(zipB64), LEVELS_DIR());
  await scanInstalledLevels();
}

// ─── Store accessors ──────────────────────────────────────────────────────────

export function getTopicsFromStore(): Topic[] { return topics; }
export function getLevelsFromStore(): Level[] { return levels; }
export function getPhrasesFromStore(): Phrase[] { return phrases; }
export function getPhraseProgressFromStore(): Record<string, PhraseProg> { return phraseProgress; }
export function getLevelProgressFromStore(): Record<string, LevelProg> { return levelProgress; }

export function setPhraseProgressEntry(phraseId: string, data: Partial<PhraseProg>): void {
  phraseProgress[phraseId] = {
    ...(phraseProgress[phraseId] ?? { learned: false, seenCount: 0 }),
    ...data,
  };
}

export function setLevelProgressEntry(levelId: string, data: Partial<LevelProg>): void {
  levelProgress[levelId] = {
    ...(levelProgress[levelId] ?? { completedSessions: 0, lastPlayedAt: null }),
    ...data,
  };
}

export function deleteLevelFromStore(levelId: string): void {
  levels = levels.filter(l => l.id !== levelId);
  phrases = phrases.filter(p => p.level_id !== levelId);
  delete phraseProgress[levelId];
  // Remove phrase progress entries for this level
  for (const key of Object.keys(phraseProgress)) {
    if (key.startsWith(levelId + '-')) delete phraseProgress[key];
  }
  delete levelProgress[levelId];
}
