import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import { Asset } from 'expo-asset';
import { unzipSync } from 'fflate';

// ─── Types ────────────────────────────────────────────────────────────────────

export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export interface Topic {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
}

export interface Level {
  id: string;
  topic_id: string;
  title: string;
  description: string;
  difficulty: CEFRLevel;
  date_added: string;
  total_phrases: number;
  source: string;
}

export interface Phrase {
  id: string;
  level_id: string;
  spanish: string;
  english: string;
  grammar_focus?: string;
  tip?: string;
  audio_path: string;
  sort_order: number;
}

export type PhraseRating = 'easy' | 'ok' | 'hard';

export interface PhraseProg {
  rating: number;
  seenCount: number;
  lastRating: PhraseRating | null;
  lastSeenAt: number | null;
}

const DEFAULT_PHRASE_PROG: PhraseProg = {
  rating: 0,
  seenCount: 0,
  lastRating: null,
  lastSeenAt: null,
};

// Migración desde el esquema antiguo ({ learned: boolean; seenCount: number }).
// Devuelve true si se detectó y migró alguna entry legacy.
function migrateLegacyPhraseProgress(
  old: Record<string, any>
): { migrated: Record<string, PhraseProg>; didMigrate: boolean } {
  const migrated: Record<string, PhraseProg> = {};
  let didMigrate = false;
  for (const [key, entry] of Object.entries(old ?? {})) {
    if (entry && typeof entry.learned === 'boolean') {
      didMigrate = true;
      migrated[key] = {
        rating: entry.learned ? -3 : 0,
        seenCount: entry.seenCount ?? 0,
        lastRating: entry.learned ? 'easy' : null,
        lastSeenAt: null,
      };
    } else if (entry && typeof entry.rating === 'number') {
      migrated[key] = {
        rating: entry.rating,
        seenCount: entry.seenCount ?? 0,
        lastRating: entry.lastRating ?? null,
        lastSeenAt: entry.lastSeenAt ?? null,
      };
    }
  }
  return { migrated, didMigrate };
}

export interface LevelProg {
  completedSessions: number;
  lastPlayedAt: string | null;
  totalListens: number;
  totalTimeSeconds: number;
}

// ─── In-memory store ──────────────────────────────────────────────────────────

let topics: Topic[] = [];
let levels: Level[] = [];
let phrases: Phrase[] = [];
let phraseProgress: Record<string, PhraseProg> = {};
let levelProgress: Record<string, LevelProg> = {};


// Versión del esquema de datos que el código de la app entiende.
// Incrementar cuando cambie la estructura de meta.json, topic.json o phrases.json.
// Debe coincidir con SCHEMA_VERSION en admin/lib/sync.py
export const APP_SCHEMA_VERSION = 1;

// ─── BUNDLED ZIPS — generated by admin/sync_mobile.py ────────────────────────
const BUNDLED_ZIPS: Record<string, { module: any; schemaVersion: number; updatedAt: string }> = {
  'daily-life-loose-phrases-A1-1': { module: require('../../assets/levels/daily-life-loose-phrases-A1-1.zip'), schemaVersion: 1, updatedAt: '2026-04-12T16:09:20' },
};
// ─── END BUNDLED ZIPS ─────────────────────────────────────────────────────────

const PROGRESS_KEY = 'progress';
const LEVELS_DIR = () => FileSystem.documentDirectory + 'levels/';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = '';
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length)));
  }
  return btoa(binary);
}

function base64ToUint8(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function extractZipBytes(bytes: Uint8Array, destDir: string): Promise<void> {
  const files = unzipSync(bytes);
  for (const [filePath, data] of Object.entries(files)) {
    if (filePath.endsWith('/')) continue;
    const fullPath = destDir + filePath;
    const dir = fullPath.substring(0, fullPath.lastIndexOf('/') + 1);
    await FileSystem.makeDirectoryAsync(dir, { intermediates: true }).catch(() => {});
    await FileSystem.writeAsStringAsync(fullPath, uint8ToBase64(data), {
      encoding: FileSystem.EncodingType.Base64,
    });
  }
}

// ─── Progress persistence ─────────────────────────────────────────────────────

export async function loadProgress(): Promise<void> {
  const raw = await AsyncStorage.getItem(PROGRESS_KEY);
  if (!raw) return;
  const p = JSON.parse(raw);
  const { migrated, didMigrate } = migrateLegacyPhraseProgress(p.phraseProgress ?? {});
  phraseProgress = migrated;
  levelProgress = p.levelProgress ?? {};
  if (didMigrate) {
    await saveProgress();
  }
}

export async function saveProgress(): Promise<void> {
  await AsyncStorage.setItem(PROGRESS_KEY, JSON.stringify({ phraseProgress, levelProgress }));
}

// ─── Level management ─────────────────────────────────────────────────────────

const DOWNLOADED_MANIFEST_PATH = () => LEVELS_DIR() + '.downloaded-manifest.json';

async function readDownloadedManifest(): Promise<Set<string>> {
  try {
    const raw = await FileSystem.readAsStringAsync(DOWNLOADED_MANIFEST_PATH());
    return new Set(JSON.parse(raw));
  } catch {
    return new Set();
  }
}

async function addToDownloadedManifest(levelId: string): Promise<void> {
  const set = await readDownloadedManifest();
  set.add(levelId);
  await FileSystem.writeAsStringAsync(DOWNLOADED_MANIFEST_PATH(), JSON.stringify([...set]));
}

export async function removeFromDownloadedManifest(levelId: string): Promise<void> {
  const set = await readDownloadedManifest();
  set.delete(levelId);
  await FileSystem.writeAsStringAsync(DOWNLOADED_MANIFEST_PATH(), JSON.stringify([...set]));
}

async function checkInstalledVersion(
  levelDir: string,
  expected: { schemaVersion: number; updatedAt: string },
): Promise<boolean> {
  try {
    const raw = await FileSystem.readAsStringAsync(levelDir + 'meta.json');
    const meta = JSON.parse(raw);
    return meta.schemaVersion === expected.schemaVersion && meta.updatedAt === expected.updatedAt;
  } catch {
    return false;
  }
}

export type ExtractProgress = {
  levelId: string;
  current: number;
  total: number;
};

export async function extractBundledLevels(
  onProgress?: (p: ExtractProgress) => void,
): Promise<void> {
  const levelsDir = LEVELS_DIR();
  await FileSystem.makeDirectoryAsync(levelsDir, { intermediates: true }).catch(() => {});

  // Cleanup: eliminar directorios que ya no están en BUNDLED_ZIPS y no son downloads del usuario
  const allDirs = await FileSystem.readDirectoryAsync(levelsDir).catch(() => [] as string[]);
  const downloadedSet = await readDownloadedManifest();
  for (const dir of allDirs) {
    if (dir.startsWith('.')) continue;
    if (!(dir in BUNDLED_ZIPS) && !downloadedSet.has(dir)) {
      await FileSystem.deleteAsync(levelsDir + dir, { idempotent: true });
    }
  }

  const entries = Object.entries(BUNDLED_ZIPS);
  const total = entries.length;

  for (let i = 0; i < entries.length; i++) {
    const [levelId, entry] = entries[i];
    const levelDir = levelsDir + levelId + '/';

    if (await checkInstalledVersion(levelDir, entry)) continue;

    onProgress?.({ levelId, current: i + 1, total });

    const info = await FileSystem.getInfoAsync(levelDir);
    if (info.exists) {
      await FileSystem.deleteAsync(levelDir, { idempotent: true });
    }

    const asset = Asset.fromModule(entry.module);
    await asset.downloadAsync();
    const zipB64 = await FileSystem.readAsStringAsync(asset.localUri!, {
      encoding: FileSystem.EncodingType.Base64,
    });
    await extractZipBytes(base64ToUint8(zipB64), levelsDir);
  }
}

export async function scanInstalledLevels(): Promise<void> {
  topics = [];
  levels = [];
  phrases = [];

  const levelsDir = LEVELS_DIR();
  const topicsById = new Map<string, Topic>();
  const entries = await FileSystem.readDirectoryAsync(levelsDir).catch(() => [] as string[]);
  for (const levelId of entries.sort()) {
    if (levelId.startsWith('.')) continue;
    const levelDir = levelsDir + levelId + '/';
    try {
      const metaRaw = await FileSystem.readAsStringAsync(levelDir + 'meta.json');
      const phrasesRaw = await FileSystem.readAsStringAsync(levelDir + 'phrases.json');
      const meta = JSON.parse(metaRaw);

      if (meta.schemaVersion !== APP_SCHEMA_VERSION) {
        console.warn(`[scan] Level ${levelId} schemaVersion=${meta.schemaVersion}, esperado ${APP_SCHEMA_VERSION}. Saltando.`);
        continue;
      }

      const phraseList: { spanish: string; english: string; grammar_focus?: string; tip?: string }[] = JSON.parse(phrasesRaw);

      levels.push({
        id: meta.id,
        topic_id: meta.topicId,
        title: meta.title,
        description: meta.description ?? '',
        difficulty: meta.difficulty,
        date_added: meta.dateAdded,
        total_phrases: phraseList.length,
        source: meta.source ?? 'bundled',
      });

      phraseList.forEach((p, i) => {
        const sortOrder = i + 1;
        const padded = String(sortOrder).padStart(3, '0');
        phrases.push({
          id: `${levelId}-${sortOrder}`,
          level_id: levelId,
          spanish: p.spanish,
          english: p.english,
          grammar_focus: p.grammar_focus || undefined,
          tip: p.tip || undefined,
          audio_path: `${levelDir}audio/${padded}.mp3`,
          sort_order: sortOrder,
        });
      });

      if (!topicsById.has(meta.topicId)) {
        try {
          const topicRaw = await FileSystem.readAsStringAsync(levelDir + 'topic.json');
          topicsById.set(meta.topicId, JSON.parse(topicRaw) as Topic);
        } catch {
          // Sin topic.json: el level queda silenciosamente sin topic visible
        }
      }
    } catch (e) {
      console.warn(`[appStore] Error cargando level ${levelId}:`, e);
    }
  }

  topics = [...topicsById.values()].sort((a, b) => a.title.localeCompare(b.title, 'es'));
}

export async function installDownloadedLevel(zipPath: string): Promise<void> {
  const zipB64 = await FileSystem.readAsStringAsync(zipPath, {
    encoding: FileSystem.EncodingType.Base64,
  });
  const bytes = base64ToUint8(zipB64);

  // Leer levelId y validar schemaVersion antes de extraer
  const files = unzipSync(bytes);
  const metaEntry = Object.entries(files).find(([p]) => p.endsWith('/meta.json'));
  if (!metaEntry) throw new Error('ZIP inválido: falta meta.json');
  const meta = JSON.parse(new TextDecoder().decode(metaEntry[1]));
  if (meta.schemaVersion !== APP_SCHEMA_VERSION) {
    throw new Error(`Level incompatible: schemaVersion=${meta.schemaVersion}, esperado ${APP_SCHEMA_VERSION}`);
  }

  await extractZipBytes(bytes, LEVELS_DIR());
  await addToDownloadedManifest(meta.id);
  await scanInstalledLevels();
}

// ─── Store accessors ──────────────────────────────────────────────────────────

export function getTopicsFromStore(): Topic[] { return topics; }
export function getLevelsFromStore(): Level[] { return levels; }
export function getPhrasesFromStore(): Phrase[] { return phrases; }
export function getPhraseProgressFromStore(): Record<string, PhraseProg> { return phraseProgress; }
export function getLevelProgressFromStore(): Record<string, LevelProg> { return levelProgress; }

export function setPhraseProgressEntry(phraseId: string, data: Partial<PhraseProg>): void {
  phraseProgress[phraseId] = {
    ...(phraseProgress[phraseId] ?? DEFAULT_PHRASE_PROG),
    ...data,
  };
}

export function setLevelProgressEntry(levelId: string, data: Partial<LevelProg>): void {
  levelProgress[levelId] = {
    ...(levelProgress[levelId] ?? { completedSessions: 0, lastPlayedAt: null, totalListens: 0, totalTimeSeconds: 0 }),
    ...data,
  };
}

export function deleteLevelFromStore(levelId: string): void {
  levels = levels.filter(l => l.id !== levelId);
  phrases = phrases.filter(p => p.level_id !== levelId);
  for (const key of Object.keys(phraseProgress)) {
    if (key.startsWith(levelId + '-')) delete phraseProgress[key];
  }
  delete levelProgress[levelId];
}
