#!/usr/bin/env python3
"""
Sincroniza todos los levels de admin/levels/ con la app móvil.

Qué hace:
  0. Copia admin/topics.json → mobile/assets/topics.json
  1. Para cada level en admin/levels/ (que tenga audio generado):
     - Genera un ZIP en mobile/assets/levels/<id>.zip
       Contenido: <id>/meta.json + <id>/phrases.json + <id>/audio/*.mp3
  2. Actualiza el bloque BUNDLED_ZIPS en mobile/src/store/appStore.ts

Solo se incluyen levels que tengan audio generado (carpeta audio/ no vacía).

Uso: python sync_mobile.py
"""
import csv
import json
import os
import shutil
import sys
import zipfile

LEVELS_DIR = os.path.join(os.path.dirname(__file__), "levels")
MOBILE_DIR = os.path.join(os.path.dirname(__file__), "..", "mobile")
ASSETS_LEVELS_OUT = os.path.join(MOBILE_DIR, "assets", "levels")
APP_STORE_TS = os.path.join(MOBILE_DIR, "src", "store", "appStore.ts")
TOPICS_JSON_SRC = os.path.join(os.path.dirname(__file__), "topics.json")
TOPICS_JSON_DST = os.path.join(MOBILE_DIR, "assets", "topics.json")


# ── helpers ──────────────────────────────────────────────────────────────────

def load_level(level_id: str) -> dict | None:
    level_dir = os.path.join(LEVELS_DIR, level_id)
    meta_path = os.path.join(level_dir, "meta.json")
    phrases_path = os.path.join(level_dir, "phrases.txt")
    audio_dir = os.path.join(level_dir, "audio")

    if not os.path.exists(meta_path) or not os.path.exists(phrases_path):
        return None

    mp3s = sorted(f for f in os.listdir(audio_dir) if f.endswith(".mp3")) if os.path.isdir(audio_dir) else []
    if not mp3s:
        print(f"  [skip] {level_id}: sin audio — ejecuta generate_audio.py {level_id} primero")
        return None

    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    phrases = []
    with open(phrases_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f, skipinitialspace=True)
        for row in reader:
            if len(row) >= 2:
                phrases.append({"spanish": row[0].strip(), "english": row[1].strip()})

    if len(phrases) != len(mp3s):
        print(f"  [warn] {level_id}: {len(phrases)} frases pero {len(mp3s)} MP3 — puede que falte regenerar audio")

    return {"meta": meta, "phrases": phrases, "mp3s": mp3s}


def load_all_levels() -> list[dict]:
    level_ids = sorted(d for d in os.listdir(LEVELS_DIR) if os.path.isdir(os.path.join(LEVELS_DIR, d)))
    levels = []
    for level_id in level_ids:
        level = load_level(level_id)
        if level:
            levels.append(level)
    return levels


# ── step 1: generate ZIPs ────────────────────────────────────────────────────

def create_level_zip(level: dict) -> None:
    level_id = level["meta"]["id"]
    level_dir = os.path.join(LEVELS_DIR, level_id)
    zip_path = os.path.join(ASSETS_LEVELS_OUT, f"{level_id}.zip")

    phrases_json = json.dumps(level["phrases"], ensure_ascii=False, indent=2)

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # meta.json
        zf.write(os.path.join(level_dir, "meta.json"), f"{level_id}/meta.json")
        # phrases.json (converted from phrases.txt)
        zf.writestr(f"{level_id}/phrases.json", phrases_json.encode("utf-8"))
        # audio files
        for mp3 in level["mp3s"]:
            zf.write(os.path.join(level_dir, "audio", mp3), f"{level_id}/audio/{mp3}")

    print(f"  [zip] {level_id}: {len(level['phrases'])} frases, {len(level['mp3s'])} mp3 → {zip_path}")


# ── step 2: update BUNDLED_ZIPS in appStore.ts ───────────────────────────────

def generate_bundled_zips_block(levels: list[dict]) -> str:
    lines = []
    lines.append("const BUNDLED_ZIPS: Record<string, any> = {")
    for level in levels:
        level_id = level["meta"]["id"]
        lines.append(f"  {repr(level_id)}: require('../../assets/levels/{level_id}.zip'),")
    lines.append("};")
    return "\n".join(lines)


def update_app_store_ts(levels: list[dict]) -> None:
    with open(APP_STORE_TS, "r", encoding="utf-8") as f:
        content = f.read()

    START_MARKER = "// ─── BUNDLED ZIPS — generated by admin/sync_mobile.py ────────────────────────"
    END_MARKER   = "// ─── END BUNDLED ZIPS ─────────────────────────────────────────────────────────"

    start = content.find(START_MARKER)
    end = content.find(END_MARKER)

    if start == -1 or end == -1:
        print("  [error] No se encontró el bloque BUNDLED_ZIPS en appStore.ts")
        sys.exit(1)

    new_block = START_MARKER + "\n" + generate_bundled_zips_block(levels) + "\n" + END_MARKER
    new_content = content[:start] + new_block + content[end + len(END_MARKER):]

    with open(APP_STORE_TS, "w", encoding="utf-8") as f:
        f.write(new_content)


# ── step 0: copy topics.json ─────────────────────────────────────────────────

def copy_topics_json() -> None:
    if not os.path.isfile(TOPICS_JSON_SRC):
        print("  [error] No se encontró admin/topics.json")
        sys.exit(1)
    shutil.copy2(TOPICS_JSON_SRC, TOPICS_JSON_DST)
    print(f"  [topics] Copiado topics.json → {TOPICS_JSON_DST}")


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    print("Copiando topics.json...")
    copy_topics_json()

    print("\nLeyendo levels...")
    levels = load_all_levels()
    if not levels:
        print("No hay levels con audio. Ejecuta generate_audio.py primero.")
        sys.exit(1)
    print(f"  {len(levels)} levels listos: {[l['meta']['id'] for l in levels]}")

    os.makedirs(ASSETS_LEVELS_OUT, exist_ok=True)

    print("\nGenerando ZIPs → mobile/assets/levels/")
    for level in levels:
        create_level_zip(level)

    print("\nActualizando BUNDLED_ZIPS en mobile/src/store/appStore.ts")
    update_app_store_ts(levels)

    total_phrases = sum(len(l["phrases"]) for l in levels)
    print(f"\n✅ Sync completado: {len(levels)} levels, {total_phrases} frases.")
    print("   Reinicia la app (no hace falta reinstalar).")


if __name__ == "__main__":
    main()
