#!/usr/bin/env python3
"""
Sincroniza todos los levels de admin/levels/ con la app móvil.

Qué hace:
  1. Para cada level en admin/levels/ (que tenga audio generado):
     - Genera un ZIP en mobile/assets/levels/<id>.zip
       Contenido: <id>/meta.json + <id>/phrases.json + <id>/topic.json + <id>/audio/*.mp3
  2. Actualiza el bloque BUNDLED_ZIPS en mobile/src/store/appStore.ts

Solo se incluyen levels que tengan audio generado (carpeta audio/ no vacía).

Uso: python sync_mobile.py
Flags:
  --no-audio  Incluye levels sin audio (útil en desarrollo). Las frases se
              empacan sin MP3; el audio se puede añadir después.
"""
import json
import os
import sys
import zipfile

LEVELS_DIR = os.path.join(os.path.dirname(__file__), "levels")
MOBILE_DIR = os.path.join(os.path.dirname(__file__), "..", "mobile")
ASSETS_LEVELS_OUT = os.path.join(MOBILE_DIR, "assets", "levels")
APP_STORE_TS = os.path.join(MOBILE_DIR, "src", "store", "appStore.ts")
TOPICS_JSON_SRC = os.path.join(os.path.dirname(__file__), "topics.json")


# ── helpers ──────────────────────────────────────────────────────────────────

def load_level(level_id: str, no_audio: bool = False) -> dict | None:
    level_dir = os.path.join(LEVELS_DIR, level_id)
    meta_path = os.path.join(level_dir, "meta.json")
    phrases_path = os.path.join(level_dir, "phrases.json")
    audio_dir = os.path.join(level_dir, "audio")

    if not os.path.exists(meta_path) or not os.path.exists(phrases_path):
        return None

    mp3s = sorted(f for f in os.listdir(audio_dir) if f.endswith(".mp3")) if os.path.isdir(audio_dir) else []
    if not mp3s and not no_audio:
        print(f"  [skip] {level_id}: sin audio — ejecuta generate_audio.py {level_id} primero")
        return None
    if not mp3s and no_audio:
        print(f"  [warn] {level_id}: sin audio (--no-audio activo)")

    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    with open(phrases_path, "r", encoding="utf-8") as f:
        raw = json.load(f)
    phrases = [
        {
            "spanish": p["es"],
            "english": p["en"],
            "grammar_focus": p.get("grammar_focus", ""),
            "tip": p.get("tip", ""),
        }
        for p in raw
        if p.get("es") and p.get("en")
    ]

    if len(phrases) != len(mp3s):
        print(f"  [warn] {level_id}: {len(phrases)} frases pero {len(mp3s)} MP3 — puede que falte regenerar audio")

    return {"meta": meta, "phrases": phrases, "mp3s": mp3s}


def load_all_levels(no_audio: bool = False) -> list[dict]:
    level_ids = sorted(d for d in os.listdir(LEVELS_DIR) if os.path.isdir(os.path.join(LEVELS_DIR, d)))
    levels = []
    for level_id in level_ids:
        level = load_level(level_id, no_audio=no_audio)
        if level:
            levels.append(level)
    return levels


# ── step 1: generate ZIPs ────────────────────────────────────────────────────

def create_level_zip(level: dict, topics_by_id: dict) -> None:
    level_id = level["meta"]["id"]
    level_dir = os.path.join(LEVELS_DIR, level_id)
    zip_path = os.path.join(ASSETS_LEVELS_OUT, f"{level_id}.zip")

    phrases_json = json.dumps(level["phrases"], ensure_ascii=False, indent=2)
    topic_id = level["meta"].get("topicId", "")
    topic_data = topics_by_id.get(topic_id)

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # meta.json
        zf.write(os.path.join(level_dir, "meta.json"), f"{level_id}/meta.json")
        zf.writestr(f"{level_id}/phrases.json", phrases_json.encode("utf-8"))
        # topic.json (para que el level sea auto-suficiente si se descarga)
        if topic_data:
            zf.writestr(f"{level_id}/topic.json", json.dumps(topic_data, ensure_ascii=False))
        # audio files (may be empty in --no-audio mode)
        for mp3 in level["mp3s"]:
            zf.write(os.path.join(level_dir, "audio", mp3), f"{level_id}/audio/{mp3}")

    audio_info = f"{len(level['mp3s'])} mp3" if level["mp3s"] else "sin audio"
    print(f"  [zip] {level_id}: {len(level['phrases'])} frases, {audio_info} → {zip_path}")


# ── step 2: update BUNDLED_ZIPS in appStore.ts ───────────────────────────────

def generate_bundled_zips_block(levels: list[dict]) -> str:
    lines = []
    lines.append("const BUNDLED_ZIPS: Record<string, any> = {")
    for level in levels:
        level_id = level["meta"]["id"]
        lines.append(f"  {repr(level_id)}: require('../../assets/levels/{level_id}.zip'),")
    lines.append("};")
    return "\n".join(lines)


def update_app_store_ts(levels: list[dict]) -> None:
    with open(APP_STORE_TS, "r", encoding="utf-8") as f:
        content = f.read()

    START_MARKER = "// ─── BUNDLED ZIPS — generated by admin/sync_mobile.py ────────────────────────"
    END_MARKER   = "// ─── END BUNDLED ZIPS ─────────────────────────────────────────────────────────"

    start = content.find(START_MARKER)
    end = content.find(END_MARKER)

    if start == -1 or end == -1:
        print("  [error] No se encontró el bloque BUNDLED_ZIPS en appStore.ts")
        sys.exit(1)

    new_block = START_MARKER + "\n" + generate_bundled_zips_block(levels) + "\n" + END_MARKER
    new_content = content[:start] + new_block + content[end + len(END_MARKER):]

    with open(APP_STORE_TS, "w", encoding="utf-8") as f:
        f.write(new_content)



# ── main ─────────────────────────────────────────────────────────────────────

def main():
    no_audio = '--no-audio' in sys.argv
    print("Leyendo levels...")
    levels = load_all_levels(no_audio=no_audio)
    if not levels:
        print("No hay levels listos. Ejecuta generate_audio.py primero (o usa --no-audio para desarrollo).")
        sys.exit(1)
    print(f"  {len(levels)} levels listos: {[l['meta']['id'] for l in levels]}")

    with open(TOPICS_JSON_SRC, "r", encoding="utf-8") as f:
        topics_by_id = {t["id"]: t for t in json.load(f)}

    os.makedirs(ASSETS_LEVELS_OUT, exist_ok=True)

    print("\nGenerando ZIPs → mobile/assets/levels/")
    for level in levels:
        create_level_zip(level, topics_by_id)

    print("\nActualizando BUNDLED_ZIPS en mobile/src/store/appStore.ts")
    update_app_store_ts(levels)

    total_phrases = sum(len(l["phrases"]) for l in levels)
    print(f"\n✅ Sync completado: {len(levels)} levels, {total_phrases} frases.")
    print("   Reinicia la app (no hace falta reinstalar).")


if __name__ == "__main__":
    main()
