"""Sincronización con la app móvil: genera ZIPs + actualiza BUNDLED_ZIPS."""
import json
import os
import sys
import zipfile
from typing import Optional

from .paths import APP_STORE_TS, ASSETS_LEVELS_OUT, LEVELS_DIR, TOPICS_JSON


class SyncResult:
    def __init__(self):
        self.synced: list[str] = []       # level ids sincronizados
        self.skipped: list[tuple[str, str]] = []  # (level_id, reason)
        self.error: str = ""


def _load_level_for_sync(level_id: str, no_audio: bool) -> Optional[dict]:
    level_dir = os.path.join(LEVELS_DIR, level_id)
    meta_path = os.path.join(level_dir, "meta.json")
    phrases_path = os.path.join(level_dir, "phrases.json")
    audio_dir = os.path.join(level_dir, "audio")

    if not os.path.exists(meta_path) or not os.path.exists(phrases_path):
        return None

    mp3s = sorted(f for f in os.listdir(audio_dir) if f.endswith(".mp3")) if os.path.isdir(audio_dir) else []
    if not mp3s and not no_audio:
        return None

    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)
    with open(phrases_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    phrases = [
        {
            "spanish": p["es"],
            "english": p["en"],
            "grammar_focus": p.get("grammar_focus", ""),
            "tip": p.get("tip", ""),
        }
        for p in raw
        if p.get("es") and p.get("en")
    ]

    return {"meta": meta, "phrases": phrases, "mp3s": mp3s}


def _create_level_zip(level: dict, topics_by_id: dict) -> None:
    level_id = level["meta"]["id"]
    level_dir = os.path.join(LEVELS_DIR, level_id)
    zip_path = os.path.join(ASSETS_LEVELS_OUT, f"{level_id}.zip")

    phrases_json = json.dumps(level["phrases"], ensure_ascii=False, indent=2)
    topic_id = level["meta"].get("topicId", "")
    topic_data = topics_by_id.get(topic_id)

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(os.path.join(level_dir, "meta.json"), f"{level_id}/meta.json")
        zf.writestr(f"{level_id}/phrases.json", phrases_json.encode("utf-8"))
        if topic_data:
            zf.writestr(f"{level_id}/topic.json", json.dumps(topic_data, ensure_ascii=False))
        for mp3 in level["mp3s"]:
            zf.write(os.path.join(level_dir, "audio", mp3), f"{level_id}/audio/{mp3}")


def _generate_bundled_zips_block(level_ids: list[str]) -> str:
    lines = ["const BUNDLED_ZIPS: Record<string, any> = {"]
    for lid in level_ids:
        lines.append(f"  {lid!r}: require('../../assets/levels/{lid}.zip'),")
    lines.append("};")
    return "\n".join(lines)


def _update_app_store_ts(level_ids: list[str]) -> None:
    with open(APP_STORE_TS, "r", encoding="utf-8") as f:
        content = f.read()

    START_MARKER = "// ─── BUNDLED ZIPS — generated by admin/sync_mobile.py ────────────────────────"
    END_MARKER = "// ─── END BUNDLED ZIPS ─────────────────────────────────────────────────────────"

    start = content.find(START_MARKER)
    end = content.find(END_MARKER)
    if start == -1 or end == -1:
        raise RuntimeError("No se encontró el bloque BUNDLED_ZIPS en appStore.ts")

    new_block = START_MARKER + "\n" + _generate_bundled_zips_block(level_ids) + "\n" + END_MARKER
    new_content = content[:start] + new_block + content[end + len(END_MARKER):]

    with open(APP_STORE_TS, "w", encoding="utf-8") as f:
        f.write(new_content)


def sync_mobile(
    candidate_level_ids: Optional[list[str]] = None,
    no_audio: bool = False,
    delete_orphan_zips: bool = True,
) -> SyncResult:
    """Sincroniza los levels indicados con mobile/.

    candidate_level_ids: si None, usa todos los directorios de admin/levels/.
    Los levels sin meta/phrases/audio se saltan automáticamente.
    """
    result = SyncResult()

    if not os.path.isdir(LEVELS_DIR):
        result.error = f"No existe {LEVELS_DIR}"
        return result

    if candidate_level_ids is None:
        candidate_level_ids = sorted(
            d for d in os.listdir(LEVELS_DIR)
            if os.path.isdir(os.path.join(LEVELS_DIR, d))
        )

    os.makedirs(ASSETS_LEVELS_OUT, exist_ok=True)

    # topics.json para topic.json embebido en cada ZIP
    try:
        with open(TOPICS_JSON, "r", encoding="utf-8") as f:
            topics_by_id = {t["id"]: t for t in json.load(f)}
    except FileNotFoundError:
        topics_by_id = {}

    loaded = []
    for level_id in candidate_level_ids:
        level = _load_level_for_sync(level_id, no_audio=no_audio)
        if level is None:
            result.skipped.append((level_id, "falta meta/phrases o sin audio"))
            continue
        loaded.append(level)

    for level in loaded:
        _create_level_zip(level, topics_by_id)
        result.synced.append(level["meta"]["id"])

    # borrar ZIPs huérfanos (que no corresponden a ningún level sincronizado)
    if delete_orphan_zips and os.path.isdir(ASSETS_LEVELS_OUT):
        kept = set(result.synced)
        for f in os.listdir(ASSETS_LEVELS_OUT):
            if f.endswith(".zip") and f[:-4] not in kept:
                try:
                    os.remove(os.path.join(ASSETS_LEVELS_OUT, f))
                except OSError:
                    pass

    try:
        _update_app_store_ts(result.synced)
    except RuntimeError as e:
        result.error = str(e)

    return result
